### ISSUE TITLE
CNVsim/Wessim Index Error 

### ISSUE THREAD

**Issue by nskelkar** [NabaviLab/CNV_Project#2]
Hello, 
I am running CNVsim with the default settings and I am experiencing this error.
Traceback (most recent call last):
  File "__sub_wessim1.py", line 818, in <module>
    main(sys.argv[1:])
  File "__sub_wessim1.py", line 177, in main
    gcVector = getFragmentUniform(abdlist, seqlist, last, isize, 1000, bind)
  File "__sub_wessim1.py", line 275, in getFragmentUniform
    seq = seqlist[ind][1]
IndexError: list index out of range

I have checked to see if my reference and targets are the same format (chr1  vs 1) and still experience this issue. Thank you

**Comment by abdelrahmanhosny** [comment]
Hi @nskelkar 
Do your reference and target files contain more than one chromosome?

**Comment by nskelkar** [comment]
Yeah they do contain more than one chromosome. Is that an issue?

**Comment by abdelrahmanhosny** [comment]
Yes, read issue #1 for more info.
The resolution is to divide your simulation (manually) for each chromosome. That is, run the simulation on chr1.fa and chr1-targets.bed separately from other chromosomes. Do so with other chromosomes as well.

**Comment by abdelrahmanhosny** [comment]
Replicated issue (refer to #1). Closing.
