### ISSUE TITLE
issue with -n total number of reads 

### ISSUE THREAD

**Issue by kumarsaurabh20** [NabaviLab/CNV_Project#3]
Every time I run CNV-Sim with different number of total reads, it generates only ~85000 reads in individual files (2 controls and 2 CNVs ). For instance, If I provide 1/10/100 million reads with -n/--n_reads parameter it still outputs same number of reads as above. 

Any suggestion??

Also, is there a parameter to set desired fold coverage?

**Comment by abdelrahmanhosny** [comment]
hey @kumarsaurabh20! 

THIS REPOSITORY IS DEPRICATED AND WILL NO LONGER BE MAINTAINED! CHECK OUR REPLACEMENT FOR THIS TOOL at https://github.com/NabaviLab/VarSimLab
