### ISSUE TITLE
Negative copy number in copynumber.bed

### ISSUE THREAD

**Issue by ZKai0801** [NabaviLab/CNV_Project#7]
Hi Dr. Hosny,

I noticed that negative copy_number value can be generated if no CNVs list file was provided. However, I couldn't understand what these negative values mean. I looked into the source code and in the function `_generateCNVMask`, you have mentioned that:

```
:return: a list of the same length as the exons list. each list item
indicates the variation to be added to the exon in the same position.
Positive number: number of amplification
Zero: no change
-1: delete this exon
```

Whereas in the following codes, negative values still be assigned to represent deletion. And those regions seem finally directed into control.fastq files. 

I'm not sure if I understand your code correct. Please point out if I have any misunderstanding.

**Comment by abdelrahmanhosny** [comment]
Hi @ZKai0801,
Your understanding is correct. The way deletions are simulated is that we introduce them in the control reference and delete it from the CNV genome (opposite to introducing amplifications).

**Comment by ZKai0801** [comment]
Hi Dr. Hosny,

I see, thank you very much for clarification!
