### ISSUE TITLE
I have a problem with output of codes

### ISSUE THREAD

**Issue by amirasalaheldin** [NabaviLab/CNV_Project#9]
Dear Dr.Hosny,
I'm a graduated student and my graduation project is based on your codes and the paper "Noise cancellation using total variation for copy number variation detection",kindly can you help me and till me what is the output of these codes and its shape.

**Comment by abdelrahmanhosny** [comment]
Hi @amirasalaheldin 
Please, have a look at the documentation in this readme file https://github.com/NabaviLab/CNV-Sim/blob/master/README.md 

If you have further questions, don't hesitate to reach out at abdelrahman.hosny@ieee.org

**Comment by amirasalaheldin** [comment]
Dear Dr.Hosny,
Thank you very much for your attention.
